### ISSUE TITLE
Add new cover film just send raw link not a file!

### ISSUE THREAD

**Issue by radespratama** [dewacahaya/submission2idc-teamproject#1]
![image](https://github.com/dewacahaya/submission2idc-teamproject/assets/56097757/f75c8512-88d7-45d6-a379-1810b638bd6c)
@dewacahaya 

Mungkin untuk bagian inputan cover film ini alangkah baiknya di ganti menjadi inputan teks biasa. Karena API yang aku siapkan itu hanya menerima teks saja bukan **file**. Jadi untuk link cover yang di kirim ke server itu seperti ini: `https://www.omdbapi.com/src/poster.jpg`

Untuk progress nya sudah lumayan, terutama UI nya udah lumayan jadi. Di tunggu untuk proses consume API nya. 

Semangat 🔥

**Comment by dewacahaya** [comment]
oooh brarti bukan input file ya kak? okelah kak thanks infonya

**Comment by radespratama** [comment]
> oooh brarti bukan input file ya kak? okelah kak thanks infonya

Yoih cuman file inputan type `text` aja
